---
title: "Lab week 8"
author: "Teresa Fukuda"
date: "11/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#load the tidyverse and read in the salmon_imports data

library(tidyverse)

salmon <- read_csv("salmon_imports.csv")

```

####Exploratory scatterplot
 
```{r}

salmon_scatter <- ggplot(salmon, aes(x=year, y=salmon_fresh)) +
  geom_point()
salmon_scatter

# Overall, this data has a very linear trend except for a weird deviation in about 2004 and 2012; generally it makes sense that the fresh salmon would increase linearly, probably only until a certain point where salmon stocks are limiting.

```
 
####Attempting a linear regression

```{r}

salmon_model <- lm(salmon_fresh ~ year, data=salmon)

salmon_model

# model linear formula: salmon imports (thousands) = -14982940 + 7550(year)


```

The linear model give an equation with an intercept of -14982940 and a slope of 7550. That means that every year, based on the data we have, the model predicts that the salmon imports will increase by 7550 thousand pounds. 


####Model diagnostics
```{r}
plot(salmon_model)

# The residuals appear to be normally distributed, based on the residual vs fitted plot that does not appear to have a patterns and the normal q-q that is very linear. 

```


